lib/main.coffee, lib/tab-bar-view.coffee, spec/tabs-spec.coffee, styles/tabs.less
Introduces user setting "Hide Tab Bar When Only One Tab Is Open" (#109)
=> Add support for hiding bar when ≤1 tab (#109)

lib/main.coffee, lib/tab-bar-view.coffee, spec/tabs-spec.coffee
“Hide Tab Bar When Only One Tab Is Open” (default to false) is now
called “Always Show Tab Bar” (default to true) describing the inverse
behavior
=> Renaming single tab setting in response to feedback

lib/tab-view.coffee, spec/tabs-spec.coffee
This PR adds a `has-path` class for tabs with a path. This will allow themes to style `<atom-text-editor>` tabs differently than tabs like the Settings or Deprecation Cop etc.
A use case would be to make active tabs have the same (seamless) color as a Syntax theme's background, but tabs like for the Settings, keep the UI colors. See https://github.com/atom/one-dark-ui/pull/11#issuecomment-73009941
ps. Not sure if there is a better way to tell if it's a `<atom-text-editor>` tab, but using `if itemPath = @item.getPath?()` seems to work.
=> Add "data-type" attribute to tabs

lib/tab-bar-view.coffee, spec/event-helpers.coffee, spec/tabs-spec.coffee
following #123 
I tested it, It works quite well and feels more reactive. Merge if you feel the need.
=> Switch tabs onmousedown

lib/tab-bar-view.coffee, spec/event-helpers.coffee, spec/tabs-spec.coffee
Pressing <kbd>Shift</kbd> + <kbd>Scroll</kbd> shouldn't switch active tab when option "Tab Scrolling" is also active.
This PR will ignore Tab Scrolling when <kbd>Shift</kbd> is pressed, taking horizontal scrolling as primary action.
Fixes https://github.com/atom/tabs/issues/139
Atom 0.200.0
Windows 8.1 64-bits
=> Shift + Scroll shouldn't switch tabs. Fixes #139

lib/main.coffee, lib/tab-bar-view.coffee, lib/tab-view.coffee, spec/tabs-spec.coffee, styles/tabs.less
Introduces new setting that opens all tabs in a temp state, allowing them to be closed when focus is changed from item to item.
Origin: ddavison/sublime-tabs#43
=> Added temporary tabs

lib/main.coffee, lib/tab-bar-view.coffee, lib/tab-view.coffee, menus/tabs.cson, spec/tabs-spec.coffee
=> Preview tab tweaks

lib/main.coffee, lib/tab-bar-view.coffee, spec/tabs-spec.coffee
Serialize the preview tab URI across restarts so the right tab is marked as a preview tab when Atom starts.
This also changes the behavior to make split tabs permanent since that seems to be consistent with editing/double-clicking a tab making it permanent
Fixes https://github.com/atom/tabs/issues/154
=> Serialize preview tab uri

lib/tab-bar-view.coffee, spec/tabs-spec.coffee
Basically does the same as #121, but with working context menu commands and added specs.
This makes the commands for closing tabs available from the command palette anywhere in the `atom-workspace` scope. This makes it possible to add keybindings for things like "Close other tabs" etc. or closing all tabs on startup.
Addresses #61.
=> Register close commands on pane level

lib/tab-bar-view.coffee, spec/tabs-spec.coffee
Force pushed an update to this pull request. This should now fix atom/atom#6662 without breaking dragging.
There's a complex interaction going on between `focus`, `mousedown`, and `dragstart` events. It seems that no matter what I try, if `document.activeElement` changes synchronously during a `mousedown` event, the subsequent `dragstart` event is never handled. There may be a hidden issue regarding our focus handling in core that would enable a more elegant fix to this, but I haven't been able to find it and would like to just fix the immediate issue for now.
=> Delay pane activation on mousedown to fix loss of focus

lib/tab-view.coffee, spec/tabs-spec.coffee
Fixes https://github.com/atom/tabs/issues/182.
Also, replaces use of `atom.project.getRepositories`, which will be removed in version 2.0, for `atom.project.repositoryForDirectory`
=> Fix tabs not showing VCS status when parent is symlink

lib/tab-view.coffee, spec/tabs-spec.coffee
Fixes https://github.com/atom/tabs/issues/183.
I haven't added tests for these changes as I feel like it's fine to verify just the *happy path* (which is already covered by existing specs). Manual testing confirmed this plays nicely with git-log and the aforementioned issue.
Thoughts? :thought_balloon: I must admit I am not super in :heart: with the code, as it adds a bit of complexity to an otherwise straightforward conditional logic. What do you think?
Thanks!
/cc: @kevinsawicki @maxbrunsfeld @nathansobo
=> Warn when disposables outside our control are not valid

menus/tabs.cson
Refs https://github.com/atom/atom/issues/3111#issuecomment-135111791
Ordering of menu items here is not ideal (it should be directly under File > Close Tab), but that's blocked on https://github.com/atom/atom/issues/6270.
/cc @atom/feedback
=> Add 'Close All Tabs' to File menu

lib/tab-bar-view.coffee
`[is=tree-view-file]` enables only the custom element that registered as
`tree-view-file` to integrate with this package's preview tabs feature.
Using `.file-tree .entry.file` allows other file tree implementations to
match the selector without having to commandeer the globally-unique
"tree-view-file" custom element name.
Fixes #208
=> Loosen selector to class names to allow integration

lib/tab-bar-view.coffee
Fixes #229.
With #222 we dropped jQuery and used a custom element to encapsulate the behavior of a `TabBarView`. When instantiating a custom element, though, any custom constructor that's set on the prototype won't be called. This means that, if we're using Coffeescript's fat arrow facility to define a method on the object's prototype, this is not going to work because of how this feature is implemented in the language. e.g.
```coffee
class Foo
something: => 1
```
It will be translated to something like the following:
```js
class A {
constructor () {
this.something = this.something.bind(this)
}
something () {
return 1
}
}
```
Since the constructor cannot be executed, `this` will be set to a wrong value. We were making use of this functionality in `::onDropOnOtherWindow`, which started to …
=> Fix bad `this` binding

lib/tab-bar-view.coffee
Refs atom/atom#9627
~~I'm not sure how to make this backwards-compatible.  I assume all it takes is a simple if block (`if x require('ipc-renderer') else require('ipc')`) but I'm not sure what the `x` would be.~~
=> Use new way of requiring Electron modules

lib/main.coffee, lib/tab-bar-view.coffee, lib/tab-view.coffee, menus/tabs.cson, spec/tabs-spec.coffee
Single-clicking opens a file in pending state and double-clicking opens a file regularly (in a non-pending state).
See corresponding changes in [atom/atom/pull/10178](https://github.com/atom/atom/pull/10178)
Addresses atom/atom/issues/9165
=> Style tab for pending item

lib/tab-bar-view.coffee, lib/tab-view.coffee, spec/tabs-spec.coffee
This adds backward-compatible checks for the new pending item APIs, and falls back to using `Item::terminatePendingState`, etc. if they're not supported in the current Atom environment.
Related to atom/atom#10995, this allows `tabs` to continue to provide visual feedback on item pendingness with both the old and new APIs; will eventually be replaced by #268.
/cc @kuychaco
=> Add support for new pending item API

lib/tab-bar-view.coffee, spec/tabs-spec.coffee
the implementation i wrote [here](https://github.com/atom/tabs/pull/273) was not quite right—it put a tab to the end _any_ time it was inserted, not only if it was a new item.
the result was that any time a tab was dragged it ended up at the end, clearly not the right behavior.
this fixes that by moving the logic up to where _new_ tabs are added, not where tabs are inserted.
=> Only add at end for new tabs

lib/tab-bar-view.coffee, spec/tabs-spec.coffee
Fixes a bug found by @maxnowack [here](https://github.com/atom/tabs/pull/276#issuecomment-210360700).
Moving tabs to the end wasn't adjusting their index in the pane, so iterating over them was out of order. 
Adding a new tab at the end calls the pane's `moveItem` method to change its position in the pane, which is then reflected in the tab bar.
The previous specs for this were only examining the tab bar's items, not the pane's items, so I added a spec which ensures that an added item is the last in the pane.
cc @lee-dohm
=> Correctly adjust pane index when adding with `addNewTabsAtEnd` config

lib/tab-bar-view.coffee, menus/tabs.cson, spec/tabs-spec.coffee
There is a Close Tabs to the Right item, so it seemed logical to me that there should be Close Tabs to the Left. I implemented this because I wanted to close tabs to the left and the option wasn't there.
=> Add 'Close Tabs to Left' right-click menu item

README.md, lib/default-file-icons.coffee, lib/file-icons.coffee, lib/main.coffee, lib/tab-bar-view.coffee, lib/tab-view.coffee, package.json, spec/default-file-icons-spec.coffee, spec/file-icons-spec.coffee
Consume `atom.file-icons` service to display icons next to file names. This is based on https://github.com/atom/atom/issues/9820 and has been suggested by @lee-dohm. Another example is available in https://github.com/atom/tree-view/pull/490.
Current behavior has been kept.
=> Consume file icon service

lib/tab-view.coffee
`tree-view` and `tabs` were expecting different outputs from the service. Sorry about that :sweat_smile:
=> Get entire icon CSS class from file icon service

lib/tab-view.coffee, spec/tabs-spec.coffee
This should fix #189.
Tab-View currently listens to the title changed event and calls various methods to update its data/view.
The problem is that the path is never set after a rename or save-as operation so those methods use out of date data.
This PR should fix this issue by listening to path changed event instead and setting `@path` correctly.
=> Listen to path changed event in addition to title changed

lib/tab-view.coffee, spec/file-icons-spec.coffee
Two problems currently exist with the package's handling of file-icons:
1. **Everything is prefixed with `icon-`**  
This is limiting for authors, who may have CSS classes named differently. It's also inconsistent with the behaviour of the `tree-panes` package, which performs no such prefixing on class-names.<br/><br/>
2. **Only one class name can be set by the service**  
Again, this is very limiting for packages that may need to add more than one class at a time (such as one for the icon, and another for its colour).
This PR alters the existing logic so that
- `icon-` prefixes are limited to "core" panels only (e.g., items with a `getIconName` method defined)
- multiple classes can be supplied by services as either an array or space-delimited list
=> Improve logic for consuming file-icons

styles/tabs.less
This patch removed needless prefixes for `flex`. Chromium supports clear `flex` since version 29
=> remove needless prefixes

lib/layout.coffee, lib/main.coffee, lib/tab-view.coffee, spec/tabs-spec.coffee, styles/layout.less
This kind of UI is really handy for those who are less keyboard-savvy, especially if you have a bunch of plots / workspace panes / consoles etc. open and don't want to remember the right sequence of commands needed to organise things :)
I'm still fairly new to CoffeeScript / Atom development so feedback is definitely appreciated. The global `@lastSplit` approach is a bit weird, but seems to be necessary as the `dragend` event gives different `clientX` and `clientY` coordinates which throws things off. I've aimed for an overlay styling that works well with both light and dark syntax / ui themes, but other suggestions are appreciated there as well.
=> Drag and drop layout management

lib/tab-bar-view.coffee, spec/tabs-spec.coffee, styles/tabs.less
Closes https://github.com/atom/tabs/issues/129
Closes https://github.com/atom/tabs/pull/300
Exactly the same as https://github.com/atom/tabs/pull/300 but using `ease-in-out` as the timing function instead of `ease-in` – thanks so much for all your hard work on this @danjordan! 🎉
=> Resize tabs when mouse moves away from tab bar (updated)

lib/layout.coffee
Determining a tab’s pane or item via the DOM is unnecessary because we store this state directly on each tab. It was leading to exceptions in cases where a tab’s pane was being removed as a side-effect of dragging because the tab didn’t have a parent element. This happens when the `core.removeEmptyPanes` config setting is enabled.
Fixes #332
=> Read pane/item directly off tab element instead of looking up via DOM

lib/tab-view.coffee, spec/file-icons-spec.coffee
**TL;DR:** This is [just fixing something I botched](https://github.com/atom/tabs/pull/319).
Formal explanation / Recap
--------------------------
Some packages may need to know *where* an icon will be used before returning a class. For example, the File-Icons package has a setting to disable icons in file tabs... in order to hide the icon though, we need to ensure the request isn't originating from the `tree-view`.
I [originally dealt with](https://github.com/atom/tabs/pull/319/files#diff-c22b992a1f1147b70fd5608ee4146a36) this issue by passing the calling TabView object as a secondary argument to `.iconClassForPath`. This gave package authors full access to the calling object's properties, allowing them to glean whatever they needed to know at that point in time.
I planned to use the …
=> Use package's name to identify context of icon-service

lib/tab-bar-view.coffee, spec/tabs-spec.coffee
Closes https://github.com/atom/tabs/issues/138
When a tab is out of view automatically scroll to that tab when activated. Current behavior is to scroll so the left or right edge is shown depending on direction.
Gifs of behavior says more than 1000 words.
=> Automatically scroll to tab if not completely visible when activating a pane item

styles/tabs.less
This fixes the position of the drop marker (that blue bar) when dragging.
I think the reason is that in recent Chromium, absolutely positioned flexbox items disregard sibling items. See https://developers.google.com/web/updates/2016/06/absolute-positioned-children
Fixes #383
=> Fix drop marker position

lib/tab-bar-view.coffee, spec/tabs-spec.coffee
In Nuclide, we're using additional PaneContainers to give people more control over their workspace.  Everything works fine for the most part, but you can't drag into the tab bar because the `fromPane` is assumed to be in the same PaneContainer. This commit removes that assumption and falls back to searching the document for the pane.
=> Account for dropping in another pane container

lib/html-helpers.coffee, lib/layout.coffee, lib/main.coffee, lib/tab-bar-view.coffee, lib/tab-view.coffee, package.json, spec/file-icons-spec.coffee, spec/tabs-spec.coffee
This pull request contains an architectural change that replaces the usage of atom-space-pen-views and custom elements respectively with raw DOM APIs and a JS object managing a non-custom DOM element internally.
As always, the scope of the change was non-trivial, so there's a risk we might have introduced some regressions. @ungb: it would be awesome if you can help preventing this by extensively testing this package (and check if popular packages that interact with `tabs` throw exceptions that could be related, e.g. calling a method that does not exist, calling a method or getting a property from a null object, etc.). ✨
=> Remove atom-space-pen-views and custom elements registration

spec/mru-list-spec.coffee, spec/tabs-spec.coffee
atom/atom#13977 adds more pane containers to the workspace, causing some of this package's tests to fail. This commit updates the tests to be a little more specific.
Not that this it doesn't add new tests to exercise dock tabs; that'll come in another PR.
=> Fix tests that docks feature broke

spec/tabs-spec.coffee
atom/atom#13977 associates a PaneContainer with its element via the
`getElement()` method (instead of the view registry). As a result,
PaneContainer must be provided with the application delegate and view
registry.
This fixes an error in that PR's tests.
=> Pass all (newly) required params to PaneContainer constructor

styles/layout.less
This goes with atom/atom#13977 and makes sure that the overlay is
visible when dragging items into closed docks.
Discussed with @simurai in that thread 😊
=> Set z-index on overlay so that it covers the docks

lib/tab-bar-view.coffee, spec/event-helpers.coffee
The security model of new Chromium versions forbids all event listeners, except for `onDragStart` and `onDrop`, to inspect the data values that have been previously set on the event's `dataTransfer` object.
To circumvent this problem we can exploit the fact that all we need to do is checking whether a boolean has been set or not. To do so, we will simply list all the items contained in the `dataTransfer` object and read their `type` property (that we use as a dictionary key), verifying that at least one of them contains the key we are searching for.
Before: 
After: 
/cc: @atom/maintainers
=> Fix missing drop indicator on Electron >= 1.14

lib/layout.coffee, lib/main.coffee, lib/tab-bar-view.coffee, lib/tab-view.coffee, spec/tabs-spec.coffee
These address the feedback in atom/atom#13977 by:
1. Only adding the close icon for dock item when `isPermanentDockItem()` returns `false` (or is absent).
2. Only allowing an item to be dropped into tab bars and panes if its `getAllowedLocations()` method includes the location (or is absent).
I updated layout to not show the overlay over disallowed locations. It would be nice to also change the cursor from copy to `no-drop` then too, but I couldn't find where this was being done.
=> Allowed Locations & Permanent Dock Items

lib/tab-bar-view.coffee, spec/tabs-spec.coffee
This pull request fixes a regression that we were observing on newer Electron versions due to reasons similar to the ones described in #426. In particular, on Electron >= 1.4 we were showing a drop indicator even for dock locations that were unsupported by the dragged item.
Analogously to the aforementioned pull request, in this one we are replacing usages of `dataTransfer.getData` in the `dragover` handler with a scan of the keys present inside the `dataTransfer` object.
/cc: @nathansobo @maxbrunsfeld
=> Fix mistakenly shown docks drop indicator on Electron >= 1.4

lib/tab-bar-view.coffee, spec/tabs-spec.coffee
Because the item's activation could result in a change of focus, we
need to wait to take it until the event has finished propagating.
Otherwise, the focus will be set by the browser as part of the default
action for the mousedown event.
Sorry there's no test but it doesn't seem possible to simulate the problematic browser behavior and still test what we want to.
=> Delay activation of item on mousedown event

spec/mru-list-spec.coffee, spec/tabs-spec.coffee
The `TextBuffer.save` method is going to become async in atom/atom#14435; instead of doing a synchronous write, it will initiate an asynchronous write and return a promise when the write completes. As a result, a few methods that depend on saving the buffer (like `Pane.close`, which is private) are now async as well. This shouldn't affect the user-facing functionality of many packages; but several packages may have test failures.
This PR updates the two tests in `tabs` that broke due to this change, so that they work regardless of whether save is synchronous or asynchronous.
=> Tweak tests so that they work when Pane.close becomes async

lib/layout.coffee, lib/main.coffee, lib/tab-bar-view.coffee, spec/file-icons-spec.coffee, spec/mru-list-spec.coffee, spec/tabs-spec.coffee
In order to add a tab bar to every pane, we iterate over every pane container on startup and call `observePanes`. Previously, every callback passed to `PaneContainer.observePanes` captured the same `location` variable from its containing scope. This caused every `TabBarView` created after startup to have its `location` set to `bottom` (the final value of the `location` variable).
This bug became more apparent after we disallowed putting TextEditors in Docks, because it meant that you couldn't drag editors between panes: TextEditors are only allowed in the `center` location, but every `TabBarView` thought it was in the `bottom` location.
I've adjusted the aforementioned code to iterate over the pane containers using `Array.forEach` so that we avoid sharing variables between the pane …
=> Fix handling of dragging pane items over tab bars

lib/tab-bar-view.coffee, spec/event-helpers.coffee, spec/tabs-spec.coffee
Fixes https://github.com/atom/atom/issues/15197
Fixes #198 
Supersedes and closes #385
Other than simplifying the code (we don't need to schedule a `setImmediate` callback to focus the item corresponding to the clicked tab), this pull-request also serves as a workaround to a Chromium bug that blocks the UI thread when middle-clicking a tab on Linux and showing a message box in the handler.
Using `click` slightly changes the UX, because left and middle click actions will be performed when users actually end the click action, rather than when they start it. Chrome, Safari and the macOS UI all behave this way, so I believe this is a good tradeoff from a user-experience standpoint.
Please, note that we still need to handle the right-click event via a `mousedown` handler, because Chromium does …
=> Perform left/middle click actions on `click` instead of on `mousedown`

lib/tab-bar-view.coffee
Fixes https://github.com/atom/atom/issues/15471
Before:
After:
/cc: @iolsen @ungb
=> Don't activate scroll-mode on middle-click when some tabs are off-screen

lib/tab-bar-view.coffee
Fixes https://github.com/atom/tabs/issues/234
Previously, when splitting an item using its tab's context menu, if the item did not have a `.copy()` method, we would try to copy the item by serializing it and then deserializing the serialized state. The problem with this is that for some items (e.g. [the tree-view](https://github.com/atom/tree-view/blob/e33e6c98616061778a0d7c8610b9d26737e61f8c/lib/tree-view-package.js#L55-L61)), deserialization always returns the same instance.
I think it's more explicit for copyable items to just implement a `.copy()` method. Before releasing this change, I need to add a `.copy` method to some of Atom's pane item classes:
=> Don't try to copy items by serializing and deserializing them

lib/main.coffee, lib/mru-list-view.js, package.json, spec/mru-list-spec.coffee
Two MRU display related improvements:
- a 150ms delay before showing the MRU tab list as suggested in #361 
- an option to disable display of the list altogether as previously attempted in #422.
=> Improve MRU tab list display

lib/main.coffee, lib/tab-view.coffee, package.json
* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions
These guards were put into place as new features were added to Atom but not yet available on stable. All the features are now in stable Atom, so the guards can be removed.
None.
Less unnecessary conditionals.
tabs will stop working on Atom versions less than 1.17.
None, but helps a little with #548
=> Remove old function guards

lib/layout.js, spec/tabs-spec.coffee
This fixes a regression from #548. The code there was `toPane ? target`, even though `toPane` was always undefined. I mistakenly moved the location check to after `toPane`'s definition, even though we should always be able to look at `target` (as a split will not affect the pane's location).
=> Don't create a split if the tab cannot be placed in the pane

spec/tabs-spec.coffee
In #550, I noticed that attempting to focus any of the layout-related specs would fail, because the layout wasn't being activated (it was being activated in some other, unrelated test). This PR handles activation/deactivation of the layout in before/afterEach calls.
=> Allow layout tests to be run individually

lib/tab-bar-view.coffee, package.json, spec/tabs-spec.coffee
* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions
Where to even start? The tabScrolling setting uses a mixed enum of booleans and strings, and declares its type as any. This _should_ be fine...except that since settings-view determines the value of a setting by looking at the HTML value, all booleans are coerced to strings. Then `atom.config.set` decides that the new stringified value is not valid as it isn't in the valid list of values for tabScrolling and ignores it. The "fix" is to explicitly declare the enum as having types boolean and string, so that `atom.config.set` will coerce the stringified …
=> Make tab scrolling settings work

lib/tab-bar-view.coffee, spec/tabs-spec.coffee
* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions
The method signature for IPC callbacks is [`(event, args...)`](https://electronjs.org/docs/api/ipc-renderer#ipcrendereronchannel-listener), but the tabs package was using `(args...)` instead. This meant that when dropping a tab onto another Atom window, the original tab would _never_ be destroyed as intended.
None.
This fixes a long-standing bug with dropping tabs on other windows, which was not discovered by the tests as they called the callback manually.
The specs are a little hacky...since the listener callback is `bind`ed, it's almost impossible to …
=>  Remove tabs correctly when dropped on another window

lib/tab-bar-view.coffee
When using Atom with Electron 3, a middle click does not close a tab. This happens, because Electron 3 is based on a Chrome version >= 55. Since then, Chrome changed how click events work. Non-primary clicks now fire the event `auxclick` rather than `click`.
See https://developers.google.com/web/updates/2016/10/auxclick and https://developer.mozilla.org/en-US/docs/Web/Events/auxclick for more information on the event.
This PR adds the `onClick` handler of TabBarView also as listener to the `auxclick` event.
None
The change fixes the problem for Electron 3 while it does have no effect in Electron 2, since the `auxclick` event never fires in this version. 
This helps with a future migration of Atom to Electron 3 and fixes the issue for unofficial distributions using Electron 3 now.
None …
=> Fix tab close on middle click for Electron 3

spec/tabs-spec.coffee
Atom has now been upgraded to use customElements inplace of
document.registerElement. We now need to attach to the DOM on some specs
=> Fix failing specs
